### ISSUE TITLE
Code for "A Hierarchical Encoder-Decoder Model for Statistical Parametric Speech Synthesis"?

### ISSUE THREAD

**Issue by dreamk73** [CSTR-Edinburgh/merlin#237]
When will the code for the work presented at Interspeech in "A Hierarchical Encoder-Decoder Model for Statistical Parametric Speech Synthesis" by @ronanki be available in Merlin? I am very interested in trying it.

**Comment by ronanki** [comment]
Thank you for your interest. 

The code was written long back and a small patch is required in order to make it compatible with latest version of Merlin. We're currently delivering the extensions we presented at Interspeech tutorial -- like adaptation, hybrid synthesis and hence this got delayed. 

We hope to release the hierarchical encoder stuff by next week.

**Comment by dreamk73** [comment]
Any update to this project?

**Comment by ronanki** [comment]
Apologies for the delay -- but this is added now.

**Comment by dreamk73** [comment]
Thank you! 

When I run run_benchmark.sh in merlin/egs/fls_blizzard2017/s1, the url to the data is not valid, so it doesn't download data files. It says:

data_url=http://datashare.is.ed.ac.uk/bitstream/handle/10283/2909/${data_dir}.zip

**Comment by ronanki** [comment]
If the direct download is not working, then download it manually from the below URL:
https://datashare.is.ed.ac.uk/handle/10283/2909

**Comment by dreamk73** [comment]
Thanks, I was able to download via your direct link. 

Now in the configuration file for conf/acoustic_fls_demo_S2SML.conf, there is a question file mentioned which is not in the repo. I couldn't find it anywhere else either. Namely:

question_file_name: %(Merlin)s/misc/questions/questions-combilex_dnn_481.hed

**Comment by ronanki** [comment]
Combilex labels and question file are licensed and can't be distributed. 

However, the recipe can use unilex labels and it's question file. I've now updated conf file accordingly. But, you need to copy [hed_feats_unilex.txt](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/questions/hed_feats_unilex.txt) to `data` directory in experiments and rename it to `hed_feats.txt` as expected [here](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/configuration/configuration.py#L243).

**Comment by dreamk73** [comment]
Can you open this issue again, as we are still debugging?

I assume in the hed_feats.txt file it says which features apply at which levels (according to the indexes after normalization). Is there an easy way to find these numbers based on a question file? 

Do I need to run run_merlin_hed.py? I see the conf file says it uses TANHE which is declared in hed_rnn.py. I think there are still some errors in run_merlin_hed.py.

            label_normaliser.prepare_dur_data(in_label_align_file_list, file_paths.seq_dur_file_list, cfg.label_type, feature_type=cfg.dur_feature_type, unit_size=cfg.dur_unit_size, feat_size=cfg.dur_feat_size)

I had to remove seq_ from the file_paths.seq_dur_file_list because it was not known. Then the next error for the same command is:

AttributeError: 'configuration' object has no attribute 'dur_unit_size'

**Comment by dreamk73** [comment]
It seems the features dur_unit_size and dur_feat_size are not incorporated in configuration/configuration.py yet.

**Comment by ronanki** [comment]
You can check how [hed_feats_unilex.txt](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/questions/hed_feats_unilex.txt) is created for [unilex question set](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/questions/questions-unilex_dnn_600.hed). One has to manually specify the question numbers for each of phone, syllable and word in QS and CQS category. There is no alternative for this and it's not that difficult to find these indices for any given question file, as they are clearly marked (`C-syl` or `C-word`). 

There're still a few places where the code was hard-wired to combilex -- but with the latest commit, everything is fixed. Run the [baseline recipe](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/fls_blizzard2017/s1/conf/acoustic_fls_demo.conf) first and then go for [hierarchical encoder-decoder recipe](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/fls_blizzard2017/s1/conf/acoustic_fls_demo_S2SML.conf).

**Comment by dreamk73** [comment]
One thing I still don't quite understand is this. The question file has 600 lines. But because you start counting at 0, you only get to 599 levels. So why does the hed_feats.txt file go to 600 and not to 599?

I was able to train models now. Per your direction, I first used the baseline recipe, then the hierarchical encoder-decoder recipe for the demo. The results after the first recipe are not great, but maybe that is also related to the small number of sentences involved in training (200). For objective costs I get:

2017-10-19 08:57:54,585     INFO           main: Develop: DNN -- MCD: 6.371 dB; BAP: 0.333 dB; F0:- RMSE: 56.989 Hz; CORR: 0.399; VUV: 9.101%
2017-10-19 08:57:54,586     INFO           main: Test   : DNN -- MCD: 6.323 dB; BAP: 0.329 dB; F0:- RMSE: 54.231 Hz; CORR: 0.413; VUV: 9.702%

But after the hierarchical encoder-decoder it is even worse. The speech sounds unintelligible and the objective costs are even higher?

2017-10-19 09:05:34,311 INFO           main    : Develop: DNN -- MCD: 8.466 dB; BAP: 0.361 dB; F0:- RMSE: 66.500 Hz; CORR: 0.252; VUV: 14.860%
2017-10-19 09:05:34,311 INFO           main    : Test   : DNN -- MCD: 8.288 dB; BAP: 0.344 dB; F0:- RMSE: 62.800 Hz; CORR: 0.175; VUV: 13.668%

**Comment by ronanki** [comment]
I have used python indices: the start index is inclusive but the end index is exclusive. I'll change this to real numbers in my next commit.

HED config file was set to run only for 5 epochs (as I was testing it) and the architectures of both the networks are completely different. I'll release the actual recipes (architecture and other settings) for full dataset very soon, where the improvements can be seen.

**Comment by dreamk73** [comment]
Thanks on clarifying the first point.

I look forward to seeing the recipes for the full dataset.

**Comment by dreamk73** [comment]
@ronanki, is there any update yet? Curious to see the actual recipes for this synthesis method.

**Comment by dreamk73** [comment]
@ronanki, I know with the winter break and lots of other things you are working on, this probably doesn't have a high priority, but is there any update to the hierarchical implementation? Do you have a full recipe that I could test?

**Comment by ronanki** [comment]
This is one of the example recipes:
http://104.131.174.95/2016_blizzard_full_MLU_slstm_ed_straight_cc.conf

I've been updating the code to enable for batch processing to speed up the training -- and hence didn't release the recipe.

**Comment by dreamk73** [comment]
I will give it a try, even if batch processing is not available yet, just to see what kind of quality we can get with it. Do you still have to run the baseline recipe first and then this one, or is this a stand-alone recipe?

**Comment by ronanki** [comment]
The quality improvement can be seen only in prosody modeling (F0 prediction). The baseline recipe has to be run, only for two processes (MAKECMP and NORMCMP).

**Comment by dreamk73** [comment]
Exactly, that is what I want to achieve is to get better prosody modeling. I am testing it out with the fls_blizzard data first.

**Comment by dreamk73** [comment]
A few questions. Since I don't have the combilex version, I changed the question file to the unilex version that was also used previously. I have trained the first step. But when I try to new model I get an error after loading the label files:

  File "/home/esther/merlin/src/run_merlin.py", line 1270, in <module>
    main_function(cfg)
  File "/home/esther/merlin/src/run_merlin.py", line 595, in main_function
    min_max_normaliser.load_min_max_values(label_norm_file)
  File "/home/esther/merlin/src/frontend/min_max_norm.py", line 82, in load_min_max_values
    min_max_vector, frame_number = io_funcs.load_binary_file_frame(label_norm_file, 1)
  File "/home/esther/merlin/src/io_funcs/binary_io.py", line 64, in load_binary_file_frame
    fid_lab = open(file_name, 'rb')
IOError: [Errno 2] No such file or directory: '/home/esther/merlin/egs/fls_blizzard2017/s1/experiments/fls_demo/acoustic_model/inter_module/label_norm_HTS_600.dat'

But there is a label_norm_HTS_609.dat file because the question file has 600 lines plus the 9 features that are added? Why is it not looking for that file? 

I also notice the line that specifies the linguistic_file_name is missing. Is it no longer needed? If so how does it know which features operate at which level?
