### ISSUE TITLE
Specified dimension not compatible with data

### ISSUE THREAD

**Issue by ishank26** [CSTR-Edinburgh/merlin#24]
Hi,
I am  implementing a base-model for DNN based TTS system using merlin frontend. Currently I'm using 50 wav files from arctic database and I have 280 binary features. However, I'm unable to proceed with output feature composition with the following error-
``` python
2016-09-17 13:32:25,526 INFO      acoustic_comp: processing file    1 of   50 : /home/neo/work/speech_iiitd/dnn_test2/data/nn_mgc_lf0_vuv_bap_199/arctic_a0001.cmp
Traceback (most recent call last):
  File "../dnn/dnn_tts/run_dnn.py", line 970, in <module>
    main_function(cfg)
  File "../dnn/dnn_tts/run_dnn.py", line 635, in main_function
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_dimension_dict, cfg.out_dimension_dict)
  File "/home/neo/work/speech_iiitd/dnn/dnn_tts/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/home/neo/work/speech_iiitd/dnn/dnn_tts/frontend/acoustic_composition.py", line 126, in prepare_data
    features, frame_number = io_funcs.load_binary_file_frame(in_file_name, in_feature_dim)
  File "/home/neo/work/speech_iiitd/dnn/dnn_tts/io_funcs/binary_io.py", line 67, in load_binary_file_frame
    assert features.size % float(dimension) == 0.0,'specified dimension %s not compatible with data'%(dimension)
AssertionError: specified dimension 5 not compatible with data
```
I'm new to dnn based speech synthesis. Kindly give some suggestions. 
Also, why do we normalize the features with [0,1].
Thanks.

My conf file-
```python

[Labels]
question_file_name:path/to/data/resources/questions_dnn_unilex-rpx_quinphone.hed 

[Outputs]
mgc    : 60
dmgc   : 180
bap    : 5  
dbap   : 15
lf0    : 1  
dlf0   : 3  

[Data]
train_file_number: 30
valid_file_number: 10
test_file_number : 10
buffer_size: 200000

[Processes]
NORMLAB  : False
MAKECMP  : True
NORMCMP  : True
TRAINDNN : False
DNNGEN   : False
GENWAV   : False
CALMCD   : False
```

**Comment by bajibabu** [comment]
Hi,

Can you check the dimension of bap features again. Isn't the default bap dimension is 1 and dbap is 3?

**Comment by ishank26** [comment]
@bajibabu 
Yes, the default dim for bap is 1. But, if I want five band aperiodicities it should 5 in my opinion. See this [file](https://github.com/CSTR-Edinburgh/merlin/blob/093464ae33d7f369bb2bd325755b18f221690361/misc/recipes/dnn/feed_forward_dnn_WORLD.conf). Am I right? Should I make any other changes?

**Comment by bajibabu** [comment]
Yes, you are right. Did you extract the parameters by yourself or using the demo's parameters? If you are using the demo's parameters then remember that bap dimension is 1 only.

**Comment by ishank26** [comment]
Yes I extracted my own parameters but did not change any values in [copy_synthesis.sh](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/copy_synthesis.sh). I am getting the "dimension mismatch...", an exception raised by [binary_io](https://github.com/CSTR-Edinburgh/merlin/blob/093464ae33d7f369bb2bd325755b18f221690361/src/io_funcs/binary_io.py)(line 50) using bap = 5.
When I used bap=1, I was able to extract the acoustic features but got another exception raised by [provider.py](https://github.com/CSTR-Edinburgh/merlin/blob/487aecbcef4e67d0b20166d84a23a389fcc18ac0/src/utils/providers.p)(line 200)- "number of frames do not match...."

Do I have to change parameters in any file (copy_synthesis ??). I'm not able to debug the issues. Need advice. 
Thanks

**Comment by gillesdegottex** [comment]
Here:
https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.sh#L58
or below, I don't see any use of the variable 'order' or any other bap-related order.

Is the bap order hard-coded in WORLD ?

**Comment by bajibabu** [comment]
Yes, it is hard-coded to 1.

**Comment by gillesdegottex** [comment]
"I was able to extract the acoustic features but got another exception raised by provider.py(line 200)- "number of frames do not match...."" This is often rised when the labels have not been updated after modifying the features (the number of frames have to almost match (within a small tolerance of a few frames)).
Just re-run the NORMLAB step and the steps below and this should be fixed.

**Comment by bajibabu** [comment]
@ishank26 
I recommend you to have a look at these scripts https://github.com/sotelo/world.py/tree/master/scripts. 
First, get aperiodicity envelop using world vocoder and then use sptk mgc2sp command to get 5-band aperiodicity as mentioned in https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/copy_synthesis.sh#L66

**Comment by ishank26** [comment]
@gillesdegottex I tried rerunning the steps from NORMLAB but the frame mismatch error persists + there is `WARNING: no silence found!` while normalizing (bap =1, fs=16000). After changing `mcep order=5` in SPTK, I'm still getting `AssertionError: specified dimension 5 not compatible with data`. @bajibabu I also ran your code given in #27, but was not successful. Am I doing something wrong?

**Comment by gillesdegottex** [comment]
Did you clear the data folder before ?
There are nasty codes that skip the computation of files if the file already exists ...

**Comment by bajibabu** [comment]
What do you mean by unsuccessful? #27 isn't merged in the master branch. For time being you can download from my repository and run the copy_synthesis.sh.

**Comment by ishank26** [comment]
@gillesdegottex, @bajibabu  Thanks :) copy_synthesis is working fine with bap = 1(conf) and order = 1(copy_synthesis.sh), however I'm still having `AssertionError: specified dimension 5 not compatible with data` with  bap = 5(conf) and order = 5(copy_synthesis.sh).

I tried using own analysis python script with -
`Dio_options=(f0_floor=71, f0_ceil=800,channels_in_octave=2.0, frame_period=5, speed=1, allowed_range=0.1) #same defaults as merlin` 
and the suggested changes by @bajibabu but stuck at "dimension 5 not compatible..."

**Comment by ronanki** [comment]
If you specify the order 5, while extracting the coefficients with the given scripts, you will end up with extracting 6 (5+1) coefficients. So, either use 6 in configuration file or change the order to 4 while extraction.

**Comment by ishank26** [comment]
@ronanki I didn't paid attention to coefficient order :| Thanks.

**Comment by Ali20177** [comment]
Hi @ronanki ,
Did you solve the mismatch dimension issue? If yes, could you please tell me how you solve it?
Thanks
